name: Remove

on:
   workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
