name: Remove

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

  - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0

   - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 0
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
